language: php
os: linux
dist: xenial

cache:
    directories:
        - $HOME/.composer/cache

git:
    depth: 1

php:
    - 7.2
    - 7.3
    - 7.4

env:
    matrix:
        - SYMFONY_VERSION="^v3.4.5" PHPUNIT_BRIDGE_VERSION="^v3.4.31" DEPENDENCIES="high"
        - SYMFONY_VERSION="^v3.4.5" PHPUNIT_BRIDGE_VERSION="^v3.4.31" DEPENDENCIES="low"
        - SYMFONY_VERSION="~v4.3.0" DEPENDENCIES="high"
        - SYMFONY_VERSION="~v4.3.0" DEPENDENCIES="low"
        - SYMFONY_VERSION="~v4.4.0" DEPENDENCIES="high"
        - SYMFONY_VERSION="~v4.4.0" DEPENDENCIES="low"
        - SYMFONY_VERSION="~v5.0.0" PHPUNIT_BRIDGE_VERSION="~v5.0.0" DEPENDENCIES="high"
        - SYMFONY_VERSION="~v5.0.0" PHPUNIT_BRIDGE_VERSION="~v5.0.0" DEPENDENCIES="low"
        - SYMFONY_VERSION="~v5.1.0" DEPENDENCIES="high"
        - SYMFONY_VERSION="~v5.1.0" DEPENDENCIES="low"
    global:
        - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-progress --no-suggest --prefer-dist"
        - PHPUNIT_BRIDGE_VERSION="~v4.4.0"

jobs:
    fast_finish: true
    include:
        - php: 7.3
          env:
              - STATIC_CHECKS=1
              - SYMFONY_VERSION="~v4.4.0"
              - DEPENDENCIES="high"

before_install:
    - phpenv config-rm xdebug.ini || return 0;
    - composer self-update
    - composer global require hirak/prestissimo -a

install:
    - php ./composer-install.php "$SYMFONY_VERSION" "$DEPENDENCIES" "$DEFAULT_COMPOSER_FLAGS" "$PHPUNIT_BRIDGE_VERSION"
    - composer show
    - if [[ "$STATIC_CHECKS" = '1' ]]; then
        travis_retry composer bin cs-fixer install -a --no-dev;
        travis_retry composer bin phpstan install -a;
      fi

script:
    - if [[ "$STATIC_CHECKS" = '1' ]]; then
        composer crunz:analyze;
        composer phpstan:check;
      fi
    - vendor/bin/phpunit
