language: php

git:
    depth: 1

php:
    - 7.1
    - 7.2
    - nightly

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly

env:
    matrix:
        - DEPENDENCIES="high"
        - DEPENDENCIES="low"
    global:
        - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-progress --no-suggest --prefer-dist"

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - phpenv config-rm xdebug.ini || return 0;
    - composer self-update

install:
    - if [[ "$DEPENDENCIES" = 'high' ]]; then
        travis_retry composer update $DEFAULT_COMPOSER_FLAGS;
      fi
    - if [[ "$DEPENDENCIES" = 'low' ]]; then
        travis_retry composer update $DEFAULT_COMPOSER_FLAGS --prefer-lowest;
      fi
    - if [[ "$DEPENDENCIES" = 'high' ]] && [[ "$TRAVIS_PHP_VERSION" = '7.2' ]]; then
        travis_retry composer bin all install -a --no-dev;
      fi

before_script:
    - composer install --prefer-source --no-interaction

script:
    - if [[ "$DEPENDENCIES" = 'high' ]] && [[ "$TRAVIS_PHP_VERSION" = '7.2' ]]; then
        composer crunz:analyze;
      fi
    - vendor/bin/phpunit
